apiVersion: v1
kind: Pod
metadata:
  name: clone-task-pv-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.ebs.csi.aws.com/zone
            operator: In
            values:
            - ap-northeast-2c
  volumes:
    - name: clone-task-pv-storage
      persistentVolumeClaim:
        claimName: clone-task-pv-claim

    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim

  containers:
    - name: clone-task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/backup"
          name: clone-task-pv-storage

        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
