apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaled
  namespace: default
spec:
  scaleTargetRef:
    name: nginx-deployment
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers:
    - type: aws-cloudwatch
      metadata:
        namespace: AWS/SQS
        dimensionName: QueueName
        dimensionValue: "scaled-queue"
        metricName: NumberOfMessagesSent
        targetMetricValue: '5'
        minMetricValue: '0'
        awsRegion: "ap-northeast-2"
        metricStat: Sum
        metricUnit: Count
        metricStatPeriod: '60'
        metricCollectionTime: '120'
        identityOwner: operator





