apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: busybox
    name: busybox
  terminationGracePeriodSeconds: 40
