apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/skills-ecr:latest
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      serviceAccountName: secret-role
