apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: nginx
          matchLabelKeys:
            - pod-template-hash
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
        ports:
        - containerPort: 80
