apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: hrdkorea
spec:
  provider:
    aws:
      service: SecretsManager
      region: <REGION-CODE>
      auth:
        jwt:
          serviceAccountRef:
            name: aws-external-secret-manager  
