apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: backend-split
  namespace: app
spec:
  service: nginx-service
  backends:
  - service: nginx-service
    weight: 50
  - service: httpd-service
    weight: 50
