apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secrets
  namespace: hrdkorea
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: secrets-manager-secret
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: hrdkorea/secret/manager/<REGION>
      property: MYSQL_USER
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: hrdkorea/secret/manager/<REGION>
      property: MYSQL_PASSWORD
  - secretKey: MYSQL_HOST
    remoteRef:
      key: hrdkorea/secret/manager/<REGION>
      property: MYSQL_HOST
  - secretKey: MYSQL_PORT
    remoteRef:
      key: hrdkorea/secret/manager/<REGION>
      property: MYSQL_PORT
  - secretKey: MYSQL_DBNAME
    remoteRef:
      key: hrdkorea/secret/manager/<REGION>
      property: MYSQL_DBNAME
  - secretKey: AWS_REGION
    remoteRef:
      key: hrdkorea/secret/manager/<REGION>
      property: AWS_REGION
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: hrdkorea
  labels:
    skills/dedicated: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      skills/dedicated: customer
  template:
    metadata:
      labels:
        skills/dedicated: customer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: skills/dedicated
                operator: In
                values:
                - customer
      containers:
        - name: customer-container
          image: <ACCOUNT_ID>.dkr.ecr.<REGION_CODE>.amazonaws.com/hrdkorea-ecr-repo:customer
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_PORT
            - name: MYSQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_DBNAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: AWS_REGION
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: hrdkorea
  labels:
    skills/dedicated: product
spec:
  replicas: 2
  selector:
    matchLabels:
      skills/dedicated: product
  template:
    metadata:
      labels:
        skills/dedicated: product
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: skills/dedicated
                operator: In
                values:
                - product
      containers:
        - name: product-container
          image: <ACCOUNT_ID>.dkr.ecr.<REGION_CODE>.amazonaws.com/hrdkorea-ecr-repo:product
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_PORT
            - name: MYSQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_DBNAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: AWS_REGION
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: hrdkorea
  labels:
    skills/dedicated: order
spec:
  replicas: 2
  selector:
    matchLabels:
      skills/dedicated: order
  template:
    metadata:
      labels:
        skills/dedicated: order
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: skills/dedicated
                operator: In
                values:
                - order
      containers:
        - name: customer-container
          image: <ACCOUNT_ID>.dkr.ecr.<REGION_CODE>.amazonaws.com/hrdkorea-ecr-repo:order
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: AWS_REGION
      restartPolicy: Always
