version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com
      - REPOSITORY_URI=950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/wsc2024-ecr
      - TAG=$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t wsc2024-ecr .
      - docker tag wsc2024-ecr:latest $REPOSITORY_URI:$TAG
      - docker tag wsc2024-ecr:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$TAG
      - docker push $REPOSITORY_URI:latest
      - echo $TAG > imageTag.txt
artifacts:
  files:
    - imageTag.txt
